const countryLanguageMap = {
    "New Zealand": "en",
    "Nicaragua": "es",
    "Bulgaria": "bg",
    "Greece": "el",
    "Jordan": "ar",
    "Hungary": "hu",
    "Czech Republic": "cs",
    "Israel": "he",
    "Hong Kong": "zh",
    "Cameroon": "fr",
    "Angola": "pt",
    "Switzerland": "de",
    "Austria": "de",
    "Honduras": "es",
    "Yemen": "ar",
    "Singapore": "en",
    "Azerbaijan": "az",
    "Ghana": "en",
    "Ethiopia": "am",
    "Sri Lanka": "si",
    "Portugal": "pt",
    "Tunisia": "ar",
    "Belgium": "fr",
    "Ivory Coast": "fr",
    "Bolivia": "es",
    "Dominican Republic": "es",
    "DR Congo": "fr",
    "Libya": "ar",
    "Venezuela": "es",
    "Chile": "es",
    "Kenya": "sw",
    "Ecuador": "es",
    "United Arab Emirates": "ar",
    "Guatemala": "es",
    "Spain": "es",
    "Algeria": "ar",
    "Canada": "en",
    "South Africa": "en",
    "Iraq": "ar",
    "Saudi Arabia": "ar",
    "Peru": "es",
    "Morocco": "ar",
    "South Korea": "ko",
    "Australia": "en",
    "Taiwan": "zh",
    "Turkey": "tr",
    "Japan": "ja",
    "Thailand": "th",
    "Egypt": "ar",
    "United Kingdom": "en",
    "Nigeria": "en",
    "France": "fr",
    "Germany": "de",
    "Colombia": "es",
    "Italy": "it",
    "Argentina": "es",
    "United States": "en",
    "Brazil": "pt",
    "Indonesia": "id",
    "Mexico": "es",
    "Philippines": "tl"
  };
  
  export default countryLanguageMap;
  